services:
  app:
    build:
      context: ./project
      dockerfile: dockerfile
    container_name: go_app
    working_dir: /app
    volumes:
      - ./project:/app
      - ./.env:/app/.env
    command: go run main.go
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379

  redis:
    image: redis:7.2-alpine
    container_name: redis
    mem_limit: 4g
    memswap_limit: 4g
    restart: always
    ports:
      - "6379:6379"